import{S as p,i}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function f(r){const t="https://pixabay.com",a="/api/",o="42750923-b31641a9e28119200a05c3b82",e=new URLSearchParams({key:o,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:21});return fetch(`${t}${a}?${e}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}function d(r){return r.map(t=>`<li class="gallery-item">
    <a href="${t.largeImageURL}" class="gallery-link">
    <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" loading="lazy"/>
    </a>
    <div class="gallery-container">
    <p class="gallery-text">Likes<span>${t.likes}</span></p>
      <p class="gallery-text">Views<span>${t.views}</span></p>
      <p class="gallery-text">Comments<span>${t.comments}</span></p>
      <p class="gallery-text">Downloads<span>${t.downloads}</span></p>
    </div>
  </li>`).join(" ")}function m(r){return u.innerHTML=d(r)}const c=document.querySelector(".loader"),u=document.querySelector(".gallery"),g=document.querySelector("form"),l=document.querySelector("input");function y(){c.classList.remove("is-hidden")}function h(){c.classList.add("is-hidden")}const L=new p(".gallery a",{captionsData:"alt",captionDelay:"250"});g.addEventListener("submit",w);function w(r){r.preventDefault(),y(),u.innerHTML="";const t=r.currentTarget.elements.field.value;t?f(t).then(a=>{a.total!==0?(m(a.hits),L.refresh(),l.value=""):(i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1}),l.value="")}).catch(a=>{i.warning({message:"Ups, something wrong bad. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1})}).finally(()=>{h()}):i.warning({message:"Please enter the name of the picture!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1})}
//# sourceMappingURL=commonHelpers.js.map
